# Generated by Django 5.0.7 on 2024-07-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('release', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('runningTime', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
