# Generated by Django 5.0.1 on 2024-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.IntegerField(max_length=24, verbose_name='관심도'),
        ),
    ]
