# Generated by Django 5.0.1 on 2024-07-17 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTools', '0001_initial'),
        ('posts', '0002_alter_post_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey( to = 'devTools.DevTool', on_delete=models.CASCADE, verbose_name='개발툴'),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='관심도'),
        ),
    ]
